name: clocky_mc_clockface
description: It's a clock written in Flutter. Have a good day, sir.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Used to render analog clock UIs
  analog_clock: ^0.1.0
  # A Flutter package to use fonts from fonts.google.com
  google_fonts: ^5.1.0
  # Contains code to deal with internationalized/localized messages
  intl: any
  # A wrapper around InheritedWidget to make them easier to use and more reusable
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true